export const categories: Record<string, string> = {
  design: "design",
  js: "javascript",
  frontend: "front-end",
  backend: "back-end",
  fullstack: "full-stack",
  uiux: "ui/ys Design",
  mobile: "mobile development",
  devops: "devops",
  ml: "machine learning",
  cybersecurity: "cybersecurity",
  datascience: "data science",
  gamedev: "game development",
  seo: "SEO & sigital marketing",
};
